### ISSUE TITLE
JCSMP implementation issue

### ISSUE THREAD

**Issue by solace-zahratabar** [SolaceSamples/solace-samples-java-jcsmp#81]
Check the JCSMP implementation from this sample:
https://github.com/SolaceSamples/solace-samples-java-jcsmp/blob/ba8ae0cfc921b9307fb7b36b80f9cd6bb3817998/src/main/java/com/solace/samples/jcsmp/patterns/GuaranteedPublisher.java#L133

So we used this sync method with exception handler and still lost the message during out tests. A strange sleep which is not acceptable for prod for 1,5 seconds and some comment leave you in an unclear situation what for that is in the sample.
https://github.com/SolaceSamples/solace-samples-java-jcsmp/blob/ba8ae0cfc921b9307fb7b36b80f9cd6bb3817998/src/main/java/com/solace/samples/jcsmp/patterns/GuaranteedPublisher.java#L151C6-L151C81

**Comment by aaron-613** [comment]
Hi @ZahraTabar , I will need some more information from you and some more details to move this Issue forward.

- What "sync method" are you referring to?  JCSMP has no synchronous publishing capabilities, it is always asynchronous to the broker.  It is only synchronous in terms of the API trying to write the message to the socket.
- How was the exception handler configured?  I assume you are referring to the `JCSMPStreamingPublishCorrelatingEventHandler`
- The "strange sleep" is to allow a graceful shutdown of the publisher, to allow any ACKs/NACKs in flight to be able to be received by the application.  If you just SHUT the connection down immediately, the application will not know the status of the last few messages that were published.
- Samples are not intended for production use.  But can I ask what is not acceptable about a graceful shutdown delay?  Perhaps it is just the client/customer not understanding how asynchronous publishing and in-flight ACKs are handled.
- Finally, how was a lost message(es) determined?  Under what specific circumstance?

Thanks!

**Comment by Mrc0113** [comment]
@ZahraTabar can you provide any further information?

**Comment by Mrc0113** [comment]
Closing as stale.
